name: Deploy static content to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./   # your site files live at repo root

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
